### ISSUE TITLE
six should be a listed requirements in setup.py install_requires

### ISSUE THREAD

**Issue by jbernardes** [darrenburns/pytest-clarity#14]
Using `pytest-clarity 0.3.0a0` with `python 3.6` leads to the following error

```
File ".tox/py3/lib/python3.6/site-packages/pytest_clarity/util.py", line 3, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by ddnomad** [comment]
The same issue with Python 3.9.1 and `pytest-clarity 0.3.0a0`. Please fix.

**Comment by aleksandr-kotlyar** [comment]
Seems that somebody made a PR #18 - which need to be reviewed and merged.
