### ISSUE TITLE
Support for unittest asserts

### ISSUE THREAD

**Issue by hugovk** [darrenburns/pytest-clarity#6]
It would be great to add support for `unittest`'s asserts.

For example:

```python
import unittest


class TestClarity(unittest.TestCase):
    def test_clarity_assert(self):

        left = [1, 2, 3]
        right = [1, 2, 4]
        assert left == right

    def test_clarity_self_assert(self):

        left = [1, 2, 3]
        right = [1, 2, 4]
        self.assertEqual(left, right)


if __name__ == "__main__":
    unittest.main()
```

`assert` is nicely coloured:

![image](https://user-images.githubusercontent.com/1324225/47216448-a2dd1180-d3ad-11e8-8a7c-aa0ebceb53cd.png)

`unittest.assertEqual` isn't:

![image](https://user-images.githubusercontent.com/1324225/47216474-b7b9a500-d3ad-11e8-8b6d-047c35396114.png)

**Comment by darrenburns** [comment]
Thanks for the suggestion!

Unfortunately `unittest` is the thing that produces the output (see here: https://github.com/python/cpython/blob/master/Lib/unittest/case.py#L1017), and so we have no control over the output of `unittest` test cases from the perspective of this plugin 😞

**Comment by nedbat** [comment]
Why leave a "wontfix" issue open?
