### ISSUE TITLE
clarity changes verbosity

### ISSUE THREAD

**Issue by okken** [darrenburns/pytest-clarity#8]
It's possible that this is on purpose, but it's jarring to me.
I have found the plugin most useful when paired with -qq to turn off automatically setting -v or -vv, not sure which.

For example, normally running pytest with no flags results in lots of dots, and with -v you get the test list and pass/fail and percentages.
With pytest-clarity, you get all that without the -v.
That's fun for a few tests, but annoying with thousands.

**Comment by danihodovic** [comment]
@darrenburns is it possible to disable the output for passing tests and just use the normal dot output?

**Comment by ionelmc** [comment]
A solution could be to activate the plugin only if verbose mode is on (user adds -vv).

**Comment by darrenburns** [comment]
I've released a new version which only activates the plugin if `-vv` is used. It also fixed the incompatibility with xdist. Thanks @ionelmc!

**Comment by danihodovic** [comment]
@darrenburns thanks!!
